version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: it-ticket-system
    ports:
      - "5002:5002"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
